config/routes.rb
Rails.application.routes.draw do
  get 'reviews/index'
  get 'reviews/show'
  get 'reviews/new'
  get 'reviews/create'
  get 'reviews/edit'
  get 'reviews/update'
  get 'reviews/destroy'
  # get 'restaurants/index'
  # get 'restaurants/show'
  # get 'restaurants/new'
  # get 'restaurants/create'
  # get 'restaurants/edit'
  # get 'restaurants/update'
  # get 'restaurants/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants
  # do
  # collection do
    # get "top", to : "restaurants#top"
  # end
  # resources :reviews
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # :name
  # :address
  # :phone_number
  # :category
  has_many :reviews, dependent: :destroy
  validates(:name, uniqueness: true, presence: true)
  validates(:address, presence: true)
  validates(:category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] })
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates(:content, presence: true)
  validates(:rating, numericality: { only_integer: true }, inclusion: { in: [0, 1, 2, 3, 4, 5] }, presence: true)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    # GET /restaurants
    @restaurants = Restaurant.all
  end

  def show
    # GET /restaurants/:id
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    # GET /restaurants/new
    @restaurant = Restaurant.new
  end

  def create
    # POST /restaurants
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    # no need for app/views/restaurnats/create.html.erb
    redirect_to restaurant_path(@restaurant)
  end

  def edit
    # GET /restaurants/:id/edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    # PATCH /restaurants/:id
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    # no need for app/views/tasks/update.html.erb
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    # DELETE /restaurants/:id
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    # no need for app/views/restaurants/destroy.html.erb
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
  # :name
  # :address
  # :phone_number
  # :category
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
  end

  def show
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def set_restaurant
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
  # :content
  # :rating
  # :restaurant
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/destroy.html.erb
<h1>Restaurants#destroy</h1>
<p>Find me in app/views/restaurants/destroy.html.erb</p>

app/views/restaurants/edit.html.erb
<h1>Restaurants#edit</h1>
<p>Find me in app/views/restaurants/edit.html.erb</p>

app/views/restaurants/index.html.erb
<!-- :name
:address
:phone_number
:category -->

<% @restaurants.each do |restaurant| %>
  <div>
    <h2><%= link_to "#{restaurant.name}", restaurant_path(restaurant.id) %></h2>
    <p>Address: <%= restaurant.address %></p>
    <p>Phone number: <%= restaurant.phone_number %></p>
    <p>Cousine: <%= restaurant.category %></p>
    <%= link_to "Delete", restaurant_path(restaurant),
      method: :delete,
      data: { confirm: "Are you sure?" } %>
  </div>
<% end %>

<p><%= link_to "Add new restaurant", new_restaurant_path %></p>

app/views/restaurants/new.html.erb
<h1>Restaurants#new</h1>
<p>Find me in app/views/restaurants/new.html.erb</p>

app/views/restaurants/show.html.erb
<!-- :name
:address
:phone_number
:category -->
<h1><%= @restaurant.name %></h1>
<h2>Address</h2>
<p><%= @restaurant.address %></p>
<h2>Phone number</h2>
<p><%= @restaurant.phone_number %></p>
<h2>Cousine</h2>
<p><%= @restaurant.category %></p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %>
<%= link_to 'Back', restaurants_path %>

<ul>
  <% @restaurant.reviews.each do |review| %>
    <li>
      <%= review.rating %>
      <%= review.content %> </li>
  <% end %>
</ul>

app/views/restaurants/update.html.erb
<h1>Restaurants#update</h1>
<p>Find me in app/views/restaurants/update.html.erb</p>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<h1 class="text-center">Post a review for <%= @restaurant.name %></h1>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <% simple_form_for [@restaurant, @review] do |f| %>
        <%= f.input :content, placeholder: "Write your review here" %>
        <%= f.submit "Post review", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/reviews/update.html.erb
<h1>Reviews#update</h1>
<p>Find me in app/views/reviews/update.html.erb</p>